name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth : 0
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "renier:"
        minor_pattern: "vargas:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: versioning
            
        
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        NEW_VERSION: ${{ steps.versioning.outputs.version }}
      run: |
        echo "Iniciando Login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Finalizando Login"
        echo "Esta es la nueva version de la imagen: [$NEW_VERSION]"


  #d

    # - name: Docker Image Build
    #   run : | 
    #     docker build -t renier1989/docker-graphql:0.0.1 .
    #     docker build -t renier1989/docker-graphql:latest .
    
    # - name: Docker Image Push
    #   run: | 
    #     docker push renier1989/docker-graphql:0.0.1
    #     docker push renier1989/docker-graphql:latest




        
      
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
